package multithreading;

class Mythread4 implements Runnable{
    public void run(){
    }
}

public class T10_GetName_Set {
    public static void main(String[] args) {
        System.out.println(Thread.currentThread().getName());  //output - Main
        Mythread4 t=new Mythread4();
        Thread th=new Thread(t);
        System.out.println(th.getName());    //output- Thread-0
        Thread.currentThread().setName("Abhishek4");
        System.out.println("New Main Name: " + Thread.currentThread().getName());  // Abhishek4

    }

}
//every thread in java has some name it may be defaulf name generated by JVM or Customized name provided by the programmer
//we can get and set name of the thread by using the following 2 method of the thread class
//public  final String getName
//public final void setName()

// we can get current executing thread object by using Thread.current thread method

//Output of the above code will be
//main
//Thread-0
//New Main Name: Abhishek4


